### PR TITLE
Hacked in steps data

### PR DESCRIPTION
**Pull request by kencaron**
Hey I was teaching myself some watchface coding and found this was open-source. I decided to try to add in steps data for my personal use. It's messy code but if you want to add in steps to engineering feel free to use this as a starting point.

I was thinking about adding in step approximation to limit the # of chars:
- 123 steps would read `123`
- 1234 steps would read `1.2K`
- 12345 steps would read `12K`

But I haven't gotten around to it (I'm much more comfortable with JS than C)

I also incorporated gulp for minifying the config pages JS code. The following should get you able to write a new `main.min.js`.

```
npm install
gulp
```

Hopefully you find it helpful. Thanks for making this face open-source!

### CODE REVIEW

**Comment by kencaron** [comment]
Hey @nguyer  just a heads up that I pushed up some bugfixes (config error, text color change error) and improvements (battery saving measures) to [my fork](https://github.com/kencaron/pebble-engineering). If you have interest I can resubmit this PR with an updated version. I also have a version for forecast.io weather sourcing (where the API key would be entered in the config page). If you wanna collaborate to get those changes into the appstore let me know, otherwise I'm thinking about pushing an alternate version to the store in about a week, assuming that's fine with you. Cheers.

**Comment by nguyer** [comment]
Hi Ken,

Wow thanks for contributing! Life is pretty busy for me these days, so I actually hadn't seen that you had a PR out there. Sorry about that. Please feel free to update it and I will try to review it as soon as possible. These sound like good improvements, so I'd be happy to include them after review.

Thanks again!

Nicko

**Comment by kcaron-cst** [comment]
Will do! I'm dogfooding the watchface a little bit. I noticed an issue yesterday where the step counter disappeared briefly and I'm trying to find the issue. I also implemented the text formatting ("1.2K").

I'll hopefully have a new PR in soon (this week).

I'll save the Forecast.io stuff for a future PR as it's fairly unrelated and could introduce new bugs anyway. Thanks again for opensourcing -- has been very helpful to see how it works.

**Comment by kencaron** [comment]
Will do! I'm dogfooding the watchface a little bit. I noticed an issue yesterday where the step counter disappeared briefly and I'm trying to find the issue. I also implemented the text formatting ("1.2K").

I'll hopefully have a new PR in soon (this week).

I'll save the Forecast.io stuff for a future PR as it's fairly unrelated and could introduce new bugs anyway. Thanks again for opensourcing -- has been very helpful to see how it works. Closing this for now -- will reopen with a new PR

**Comment by nguyer** [comment]
Awesome! Thanks for adding the steps! That will be a great feature!

**Pull request closed without merging**
